
export const RETRIEVE_USERINFO_SUCCESS = 'RETRIEVE_USERINFO_SUCCESS';
export const RETRIEVE_LOGIN_SUCCESS = 'RETRIEVE_LOGIN_SUCCESS';
export const RETRIEVE_HAPPYINDEX_SUCCESS = 'RETRIEVE_LOGIN_SUCCESS';

export const RETRIEVE_CURATED_ITEMS_SUCCESS = 'RETRIEVE_CURATED_ITEMS_SUCCESS';
export const RETRIEVE_NEAR_ITEMS_SUCCESS = 'RETRIEVE_NEAR_ITEMS_SUCCESS';
export const RETRIEVE_ITEMS_LIST_SUCCESS = 'RETRIEVE_ITEMS_LIST_SUCCESS';
export const RETRIEVE_ITEM_DETAILS_SUCCESS = 'RETRIEVE_ITEM_DETAILS_SUCCESS';
export const RETRIEVE_ITEMS_SEARCH_RESULT_SUCCESS = 'RETRIEVE_ITEMS_SEARCH_RESULT_SUCCESS';

export const RETRIEVE_MOVIES_GENRES_SUCCESS = 'RETRIEVE_MOVIES_GENRES_SUCCESS';

export const RETRIEVE_POPULAR_MOVIES_SUCCESS = 'RETRIEVE_POPULAR_MOVIES_SUCCESS';
export const RETRIEVE_NOWPLAYING_MOVIES_SUCCESS = 'RETRIEVE_NOWPLAYING_MOVIES_SUCCESS';
export const RETRIEVE_MOVIES_LIST_SUCCESS = 'RETRIEVE_MOVIES_LIST_SUCCESS';
export const RETRIEVE_MOVIE_DETAILS_SUCCESS = 'RETRIEVE_MOVIE_DETAILS_SUCCESS';
export const RETRIEVE_MOVIES_SEARCH_RESULT_SUCCESS = 'RETRIEVE_MOVIES_SEARCH_RESULT_SUCCESS';
